name 'ecology-cluster'
maintainer 'Battelle PNNL'
maintainer_email 'david.brown@pnnl.gov'
license 'all_rights'
description 'Installs/Configures ecology-cluster'
long_description 'Installs/Configures ecology-cluster'
version '0.1.0'

depends 'slurm'
depends 'hostsfile'
depends 'nfs'
