name 'ecology-cluster'
maintainer 'Battelle PNNL'
maintainer_email 'david.brown@pnnl.gov'
license 'all_rights'
description 'Installs/Configures ecology-cluster'
long_description 'Installs/Configures ecology-cluster'
version '0.1.3'
issues_url 'https://github.com/Ecy-public/ecology-cluster-cookbook/issues'
source_url 'https://github.com/Ecy-public/ecology-cluster-cookbook'

depends 'chef-client'
depends 'omnibus_updater'
depends 'yum'
depends 'yum-centos'
depends 'yum-epel'
depends 'hostsfile'
depends 'nfs'
depends 'lvm'
depends 'apache2'
depends 'build-essential'
